# Generated by Django 4.1.3 on 2023-01-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('despatched', 'despatched'), ('in-transit', 'in-transit'), ('cancelled', 'cancelled')], default='in-cart', max_length=200),
        ),
    ]
